"""Public alignment API for configuration, schedules, losses, and execution."""

from __future__ import annotations

from tomojax.align._geometry.geometry_applier import BaseGeometryArrays, apply_alignment_state
from tomojax.align._geometry.geometry_blocks import (
    GeometryCalibrationState,
    geometry_with_axis_state,
    level_detector_grid,
    normalize_geometry_dofs,
    summarize_geometry_calibration_stats,
)
from tomojax.align._geometry.parametrizations import se3_from_5d
from tomojax.align._model.dof_specs import DofSpec, dof_spec
from tomojax.align._model.dofs import DofBounds, normalize_alignment_dofs, normalize_bounds
from tomojax.align._model.gauge import GaugeFixMode
from tomojax.align._model.schedules import (
    PUBLIC_SCHEDULE_PRESETS,
    AlignmentSchedule,
    AlignmentStage,
    GaugePolicy,
    ResolvedAlignmentSchedule,
    ResolvedAlignmentStage,
    resolve_alignment_schedule,
    schedule_preset,
)
from tomojax.align._model.state import AlignmentState, PoseState, SetupGeometryState
from tomojax.align._objectives.loss_adapters import LossAdapter, build_loss_adapter
from tomojax.align._objectives.loss_specs import (
    AlignmentLossConfig,
    AlignmentLossSchedule,
    AlignmentLossSpec,
    EdgeL2LossSpec,
    L2LossSpec,
    L2OtsuLossSpec,
    LossScheduleEntry,
    PWLSLossSpec,
    loss_spec_name,
    loss_spec_params,
    parse_loss_schedule,
    parse_loss_spec,
    resolve_loss_for_level,
    validate_loss_schedule_levels,
)
from tomojax.align._profiles import (
    AlignmentProfile,
    AlignmentProfileInput,
    AlignmentProfilePolicy,
    FallbackPolicy,
    QualityTier,
    alignment_profile_policy,
    normalize_alignment_profile,
    profile_policy_from_config,
    resolve_profiled_cli_defaults,
)
from tomojax.align.io.checkpoint import (
    AlignmentCheckpointGeometrySnapshot,
    AlignmentCheckpointMetadataInput,
    AlignmentCheckpointProgress,
    AlignmentProjectionIdentity,
    CheckpointError,
    CheckpointMetadata,
    build_alignment_checkpoint_metadata_from_input,
    load_alignment_checkpoint,
    save_alignment_checkpoint,
    validate_alignment_checkpoint,
)
from tomojax.align.io.params_export import save_alignment_params_csv, save_alignment_params_json
from tomojax.align.pipeline import (
    AlignConfig,
    AlignMultiresResumeState,
    AlignResumeState,
    OuterStat,
    OuterStatValue,
    align,
    align_multires,
)

__all__ = [
    "PUBLIC_SCHEDULE_PRESETS",
    "AlignConfig",
    "AlignMultiresResumeState",
    "AlignResumeState",
    "AlignmentCheckpointGeometrySnapshot",
    "AlignmentCheckpointMetadataInput",
    "AlignmentCheckpointProgress",
    "AlignmentLossConfig",
    "AlignmentLossSchedule",
    "AlignmentLossSpec",
    "AlignmentProfile",
    "AlignmentProfileInput",
    "AlignmentProfilePolicy",
    "AlignmentProjectionIdentity",
    "AlignmentSchedule",
    "AlignmentStage",
    "AlignmentState",
    "BaseGeometryArrays",
    "CheckpointError",
    "CheckpointMetadata",
    "DofBounds",
    "DofSpec",
    "EdgeL2LossSpec",
    "FallbackPolicy",
    "GaugeFixMode",
    "GaugePolicy",
    "GeometryCalibrationState",
    "L2LossSpec",
    "L2OtsuLossSpec",
    "LossAdapter",
    "LossScheduleEntry",
    "OuterStat",
    "OuterStatValue",
    "PWLSLossSpec",
    "PoseState",
    "QualityTier",
    "ResolvedAlignmentSchedule",
    "ResolvedAlignmentStage",
    "SetupGeometryState",
    "align",
    "align_multires",
    "alignment_profile_policy",
    "apply_alignment_state",
    "build_alignment_checkpoint_metadata_from_input",
    "build_loss_adapter",
    "dof_spec",
    "geometry_with_axis_state",
    "level_detector_grid",
    "load_alignment_checkpoint",
    "loss_spec_name",
    "loss_spec_params",
    "normalize_alignment_dofs",
    "normalize_alignment_profile",
    "normalize_bounds",
    "normalize_geometry_dofs",
    "parse_loss_schedule",
    "parse_loss_spec",
    "profile_policy_from_config",
    "resolve_alignment_schedule",
    "resolve_loss_for_level",
    "resolve_profiled_cli_defaults",
    "save_alignment_checkpoint",
    "save_alignment_params_csv",
    "save_alignment_params_json",
    "schedule_preset",
    "se3_from_5d",
    "summarize_geometry_calibration_stats",
    "validate_alignment_checkpoint",
    "validate_loss_schedule_levels",
]
