[project]
authors = ["Tristan Manchester <tristan.manchester@diamond.ac.uk>"]
name = "tomojax"
version = "0.1.0"
channels = ["conda-forge", "nvidia"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
tifffile = ">=2025.8.28,<2026"
matplotlib = ">=3.10.5,<4"
numpy = ">=2.3.2,<3"
scikit-image = ">=0.25.2,<0.26"
psutil = ">=7.0.0,<8"
scipy = ">=1.16.1,<2"
tqdm = ">=4.67.1,<5"
cudnn = "*"

[pypi-dependencies]
jax = { version = ">=0.5.3,<0.6", extras = ["cuda12"] }
optax = "*"

[system-requirements]
cuda = "12"

[tasks]
test-gpu = "python -c \"import jax; print(f'JAX backend: {jax.default_backend()}'); print(f'Devices: {jax.devices()}')\""