[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "tomojax"
version = "0.2.0"
description = "TomoJAX — CT projector, reconstruction, and alignment (v2)"
requires-python = ">=3.8"
authors = [{ name = "TomoJAX contributors" }]
dependencies = []

[tool.hatch.build.targets.wheel]
packages = ["src/tomojax"]
