from __future__ import annotations

from collections.abc import Iterator, MutableMapping
from pathlib import Path
from typing import Any, overload

import numpy as np
from numpy.typing import DTypeLike

class AttributeManager(MutableMapping[str, object]):
    @overload
    def get(self, key: str, default: None = None) -> object | None: ...
    @overload
    def get(self, key: str, default: object) -> object: ...
    def __getitem__(self, key: str) -> object: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...

class Dataset:
    attrs: AttributeManager
    shape: tuple[int, ...]
    ndim: int
    size: int | None
    dtype: np.dtype[Any]
    def __getitem__(self, key: object) -> object: ...
    def astype(self, dtype: DTypeLike) -> Dataset: ...

class Group:
    attrs: AttributeManager
    @overload
    def get(self, name: str, default: None = None) -> Dataset | Group | None: ...
    @overload
    def get(self, name: str, default: object) -> Dataset | Group | object: ...
    def require_group(self, name: str) -> Group: ...
    def create_group(self, name: str) -> Group: ...
    def create_dataset(self, name: str, data: object = ..., **kwargs: object) -> Dataset: ...
    def __contains__(self, name: object) -> bool: ...
    def __getitem__(self, name: str) -> Dataset | Group: ...
    def __delitem__(self, name: str) -> None: ...

class File(Group):
    def __init__(self, name: str | Path, mode: str = "r", **kwargs: object) -> None: ...
    def __enter__(self) -> File: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

def is_hdf5(name: str | Path) -> bool: ...
