"""Small production facade for geometry.

The package root keeps stable geometry objects and commonly used product
helpers. The broader developer-oriented surface remains available from
``tomojax.geometry.api``.
"""

from tomojax.geometry.api import (
    CORE_X_AXIS,
    CORE_Y_AXIS,
    CORE_Z_AXIS,
    DISK_VOLUME_AXES,
    INTERNAL_VOLUME_AXES,
    VOLUME_AXES_ATTR,
    CalibrationState,
    CalibrationVariable,
    Detector,
    Geometry,
    GeometryState,
    Grid,
    LaminographyGeometry,
    ParallelGeometry,
    RotationAxisGeometry,
    axes_to_perm,
    axis_pose_stack,
    axis_unit_from_rotations,
    build_calibrated_geometry_metadata_patch,
    build_calibration_manifest,
    compute_roi,
    cylindrical_mask_xy,
    detector_grid_from_calibration,
    detector_grid_from_geometry_inputs,
    grid_from_detector_fov,
    grid_from_detector_fov_cube,
    grid_from_detector_fov_slices,
    grid_volume_origin,
    infer_disk_axes,
    nominal_axis_unit_from_inputs,
    read_geometry_json,
    read_pose_params_csv,
    stack_view_poses,
    transpose_volume,
    validate_calibration_gauges,
)

__all__ = [
    "CORE_X_AXIS",
    "CORE_Y_AXIS",
    "CORE_Z_AXIS",
    "DISK_VOLUME_AXES",
    "INTERNAL_VOLUME_AXES",
    "VOLUME_AXES_ATTR",
    "CalibrationState",
    "CalibrationVariable",
    "Detector",
    "Geometry",
    "GeometryState",
    "Grid",
    "LaminographyGeometry",
    "ParallelGeometry",
    "RotationAxisGeometry",
    "axes_to_perm",
    "axis_pose_stack",
    "axis_unit_from_rotations",
    "build_calibrated_geometry_metadata_patch",
    "build_calibration_manifest",
    "compute_roi",
    "cylindrical_mask_xy",
    "detector_grid_from_calibration",
    "detector_grid_from_geometry_inputs",
    "grid_from_detector_fov",
    "grid_from_detector_fov_cube",
    "grid_from_detector_fov_slices",
    "grid_volume_origin",
    "infer_disk_axes",
    "nominal_axis_unit_from_inputs",
    "read_geometry_json",
    "read_pose_params_csv",
    "stack_view_poses",
    "transpose_volume",
    "validate_calibration_gauges",
]
