"""Public geometry helpers for TomoJAX."""

from tomojax.geometry.api import (
    DISK_VOLUME_AXES,
    INTERNAL_VOLUME_AXES,
    VOLUME_AXES_ATTR,
    CanonicalizedGeometry,
    GaugeReport,
    GaugeTransfer,
    GeometryState,
    PoseParameters,
    RoiInfo,
    ScalarParameter,
    SetupParameters,
    axes_to_perm,
    canonicalize_geometry_gauges,
    compute_roi,
    cylindrical_mask_xy,
    grid_from_detector_fov,
    grid_from_detector_fov_cube,
    grid_from_detector_fov_slices,
    infer_disk_axes,
    is_shape_xyz,
    is_shape_zyx,
    transpose_volume,
)

__all__ = [
    "DISK_VOLUME_AXES",
    "INTERNAL_VOLUME_AXES",
    "VOLUME_AXES_ATTR",
    "CanonicalizedGeometry",
    "GaugeReport",
    "GaugeTransfer",
    "GeometryState",
    "PoseParameters",
    "RoiInfo",
    "ScalarParameter",
    "SetupParameters",
    "axes_to_perm",
    "canonicalize_geometry_gauges",
    "compute_roi",
    "cylindrical_mask_xy",
    "grid_from_detector_fov",
    "grid_from_detector_fov_cube",
    "grid_from_detector_fov_slices",
    "infer_disk_axes",
    "is_shape_xyz",
    "is_shape_zyx",
    "transpose_volume",
]
