"""Public API for geometry metadata, axes, and field-of-view helpers."""

from tomojax.core.geometry import (
    Detector,
    Geometry,
    Grid,
    LaminographyGeometry,
    ParallelGeometry,
    RotationAxisGeometry,
    normalize_axis_unit,
)
from tomojax.core.geometry.views import stack_view_poses
from tomojax.geometry._axes import (
    CORE_X_AXIS,
    CORE_Y_AXIS,
    CORE_Z_AXIS,
    DET_U_VOLUME_AXIS,
    DET_V_VOLUME_AXIS,
    DISK_VOLUME_AXES,
    INTERNAL_VOLUME_AXES,
    TOMO_AXIS,
    TOMO_ROTATION_PLANE_AXES,
    VOLUME_AXES_ATTR,
    axes_to_perm,
    infer_disk_axes,
    is_shape_xyz,
    is_shape_zyx,
    transpose_volume,
)
from tomojax.geometry._axis_geometry import (
    AXIS_DIRECTION_DOFS,
    axis_pose_stack,
    axis_rotations_from_active,
    axis_unit_from_active,
    axis_unit_from_rotations,
    axis_values_from_rotations,
    default_active_axis_dofs,
    nominal_axis_unit_from_inputs,
)
from tomojax.geometry._calibration_conventions import ConventionAudit, ConventionEvidence
from tomojax.geometry._calibration_gauge import GaugeValidationError, validate_calibration_gauges
from tomojax.geometry._calibration_manifest import (
    build_calibrated_geometry_metadata_patch,
    build_calibration_manifest,
)
from tomojax.geometry._calibration_objectives import CandidateScore, MetricSpec, ObjectiveCard
from tomojax.geometry._calibration_state import CalibrationState, CalibrationVariable
from tomojax.geometry._calibration_units import DetectorPixelScale, DetectorPixelValue
from tomojax.geometry._detector_grid import (
    detector_grid_from_calibration,
    detector_grid_from_center_offset,
    detector_grid_from_detector_roll,
    detector_grid_from_geometry_inputs,
    offset_detector_grid,
    transform_detector_grid,
    zero_center_detector_grid,
)
from tomojax.geometry._fov import (
    RoiInfo,
    compute_roi,
    cylindrical_mask_xy,
    grid_from_detector_fov,
    grid_from_detector_fov_cube,
    grid_from_detector_fov_slices,
)
from tomojax.geometry._gauges import (
    CanonicalizedGeometry,
    GaugeReport,
    GaugeTransfer,
    canonicalize_geometry_gauges,
)
from tomojax.geometry._serialization import (
    GEOMETRY_STATE_SCHEMA_VERSION,
    geometry_state_from_dict,
    geometry_state_to_dict,
    read_geometry_json,
    read_pose_params_csv,
    write_geometry_json,
    write_pose_decomposition_csv,
    write_pose_params_csv,
)
from tomojax.geometry._state import (
    AcquisitionParameters,
    GeometryState,
    PoseParameters,
    ScalarParameter,
    SetupParameters,
)

__all__ = [
    "AXIS_DIRECTION_DOFS",
    "CORE_X_AXIS",
    "CORE_Y_AXIS",
    "CORE_Z_AXIS",
    "DET_U_VOLUME_AXIS",
    "DET_V_VOLUME_AXIS",
    "DISK_VOLUME_AXES",
    "GEOMETRY_STATE_SCHEMA_VERSION",
    "INTERNAL_VOLUME_AXES",
    "TOMO_AXIS",
    "TOMO_ROTATION_PLANE_AXES",
    "VOLUME_AXES_ATTR",
    "AcquisitionParameters",
    "CalibrationState",
    "CalibrationVariable",
    "CandidateScore",
    "CanonicalizedGeometry",
    "ConventionAudit",
    "ConventionEvidence",
    "Detector",
    "DetectorPixelScale",
    "DetectorPixelValue",
    "GaugeReport",
    "GaugeTransfer",
    "GaugeValidationError",
    "Geometry",
    "GeometryState",
    "Grid",
    "LaminographyGeometry",
    "MetricSpec",
    "ObjectiveCard",
    "ParallelGeometry",
    "PoseParameters",
    "RoiInfo",
    "RotationAxisGeometry",
    "ScalarParameter",
    "SetupParameters",
    "axes_to_perm",
    "axis_pose_stack",
    "axis_rotations_from_active",
    "axis_unit_from_active",
    "axis_unit_from_rotations",
    "axis_values_from_rotations",
    "build_calibrated_geometry_metadata_patch",
    "build_calibration_manifest",
    "canonicalize_geometry_gauges",
    "compute_roi",
    "cylindrical_mask_xy",
    "default_active_axis_dofs",
    "detector_grid_from_calibration",
    "detector_grid_from_center_offset",
    "detector_grid_from_detector_roll",
    "detector_grid_from_geometry_inputs",
    "geometry_state_from_dict",
    "geometry_state_to_dict",
    "grid_from_detector_fov",
    "grid_from_detector_fov_cube",
    "grid_from_detector_fov_slices",
    "infer_disk_axes",
    "is_shape_xyz",
    "is_shape_zyx",
    "nominal_axis_unit_from_inputs",
    "normalize_axis_unit",
    "offset_detector_grid",
    "read_geometry_json",
    "read_pose_params_csv",
    "stack_view_poses",
    "transform_detector_grid",
    "transpose_volume",
    "validate_calibration_gauges",
    "write_geometry_json",
    "write_pose_decomposition_csv",
    "write_pose_params_csv",
    "zero_center_detector_grid",
]
