"""Public alignment API for configuration, schedules, losses, and execution."""

from __future__ import annotations

from tomojax.alignment._config import coupled_pose_config, resolved_schedule_for_config
from tomojax.alignment._geometry.geometry_applier import BaseGeometryArrays, apply_alignment_state
from tomojax.alignment._geometry.geometry_blocks import (
    GeometryCalibrationState,
    geometry_with_axis_state,
    level_detector_grid,
    normalize_geometry_dofs,
    summarize_geometry_calibration_stats,
)
from tomojax.alignment._geometry.parametrizations import (
    PoseTranslationFrame,
    apply_pose_update,
    apply_pose_updates,
    pad_pose_params,
    se3_from_5d,
)
from tomojax.alignment._model.dof_specs import DofSpec, dof_spec
from tomojax.alignment._model.dofs import (
    DOF_NAMES,
    POSE_WIDTH,
    DofBounds,
    normalize_alignment_dofs,
    normalize_bounds,
)
from tomojax.alignment._model.gauge import GaugeFixMode
from tomojax.alignment._model.schedules import (
    PUBLIC_SCHEDULE_PRESETS,
    AlignmentSchedule,
    AlignmentStage,
    GaugePolicy,
    GaugePolicyError,
    ResolvedAlignmentSchedule,
    ResolvedAlignmentStage,
    resolve_alignment_schedule,
    schedule_preset,
)
from tomojax.alignment._model.state import AlignmentState, PoseState, SetupGeometryState
from tomojax.alignment._modes import (
    MODES,
    AlignmentMode,
    AlignmentPlan,
    ConeSetup,
    alignment_plan,
    cone_setup,
    normalize_mode,
)
from tomojax.alignment._objectives.loss_adapters import LossAdapter, build_loss_adapter
from tomojax.alignment._objectives.loss_specs import (
    AlignmentLossConfig,
    AlignmentLossSchedule,
    AlignmentLossSpec,
    EdgeL2LossSpec,
    L2LossSpec,
    L2OtsuLossSpec,
    LossScheduleEntry,
    PWLSLossSpec,
    loss_spec_name,
    loss_spec_params,
    parse_loss_schedule,
    parse_loss_spec,
    resolve_loss_for_level,
    validate_loss_schedule_levels,
)
from tomojax.alignment._prealign import fold_detector_offset, implied_detector_offset
from tomojax.alignment._profiles import (
    AlignmentProfile,
    AlignmentProfileInput,
    AlignmentProfilePolicy,
    FallbackPolicy,
    QualityTier,
    alignment_profile_policy,
    normalize_alignment_profile,
    profile_policy_from_config,
    resolve_profiled_cli_defaults,
)
from tomojax.alignment.io.checkpoint import (
    AlignmentCheckpoint,
    AlignmentCheckpointGeometrySnapshot,
    AlignmentCheckpointMetadataInput,
    AlignmentCheckpointProgress,
    AlignmentProjectionIdentity,
    CheckpointError,
    CheckpointMetadata,
    ScheduleResumeState,
    build_alignment_checkpoint_metadata_from_input,
    load_alignment_checkpoint,
    normalize_schedule_resume_state,
    save_alignment_checkpoint,
    validate_alignment_checkpoint,
)
from tomojax.alignment.io.params_export import (
    alignment_params_payload,
    save_alignment_params_csv,
    save_alignment_params_json,
)
from tomojax.alignment.pipeline import (
    AlignConfig,
    AlignInfo,
    AlignMultiresInfo,
    AlignMultiresResumeState,
    AlignResumeState,
    OuterStat,
    OuterStatValue,
    align,
    align_multires,
)

__all__ = [
    "DOF_NAMES",
    "MODES",
    "POSE_WIDTH",
    "PUBLIC_SCHEDULE_PRESETS",
    "AlignConfig",
    "AlignInfo",
    "AlignMultiresInfo",
    "AlignMultiresResumeState",
    "AlignResumeState",
    "AlignmentCheckpoint",
    "AlignmentCheckpointGeometrySnapshot",
    "AlignmentCheckpointMetadataInput",
    "AlignmentCheckpointProgress",
    "AlignmentLossConfig",
    "AlignmentLossSchedule",
    "AlignmentLossSpec",
    "AlignmentMode",
    "AlignmentPlan",
    "AlignmentProfile",
    "AlignmentProfileInput",
    "AlignmentProfilePolicy",
    "AlignmentProjectionIdentity",
    "AlignmentSchedule",
    "AlignmentStage",
    "AlignmentState",
    "BaseGeometryArrays",
    "CheckpointError",
    "CheckpointMetadata",
    "ConeSetup",
    "DofBounds",
    "DofSpec",
    "EdgeL2LossSpec",
    "FallbackPolicy",
    "GaugeFixMode",
    "GaugePolicy",
    "GaugePolicyError",
    "GeometryCalibrationState",
    "L2LossSpec",
    "L2OtsuLossSpec",
    "LossAdapter",
    "LossScheduleEntry",
    "OuterStat",
    "OuterStatValue",
    "PWLSLossSpec",
    "PoseState",
    "PoseTranslationFrame",
    "QualityTier",
    "ResolvedAlignmentSchedule",
    "ResolvedAlignmentStage",
    "ScheduleResumeState",
    "SetupGeometryState",
    "align",
    "align_multires",
    "alignment_params_payload",
    "alignment_plan",
    "alignment_profile_policy",
    "apply_alignment_state",
    "apply_pose_update",
    "apply_pose_updates",
    "build_alignment_checkpoint_metadata_from_input",
    "build_loss_adapter",
    "cone_setup",
    "coupled_pose_config",
    "dof_spec",
    "fold_detector_offset",
    "geometry_with_axis_state",
    "implied_detector_offset",
    "level_detector_grid",
    "load_alignment_checkpoint",
    "loss_spec_name",
    "loss_spec_params",
    "normalize_alignment_dofs",
    "normalize_alignment_profile",
    "normalize_bounds",
    "normalize_geometry_dofs",
    "normalize_mode",
    "normalize_schedule_resume_state",
    "pad_pose_params",
    "parse_loss_schedule",
    "parse_loss_spec",
    "profile_policy_from_config",
    "resolve_alignment_schedule",
    "resolve_loss_for_level",
    "resolve_profiled_cli_defaults",
    "resolved_schedule_for_config",
    "save_alignment_checkpoint",
    "save_alignment_params_csv",
    "save_alignment_params_json",
    "schedule_preset",
    "se3_from_5d",
    "summarize_geometry_calibration_stats",
    "validate_alignment_checkpoint",
    "validate_loss_schedule_levels",
]
