"""Shared benchmark helpers and reusable benchmark-facing utilities."""

from .alignment_scenarios import (
    AcquisitionSpec,
    AlignmentScenario,
    PhantomSpec,
    ScenarioExpectation,
    ScenarioSuite,
    phantom_spec,
    scenario_by_slug,
    scenario_catalog,
    scenario_suite,
    validate_scenario_catalog,
)
from .forward_projector import (
    ForwardProjectorBenchmarkConfig,
    ForwardProjectorSuiteCase,
    ForwardSinogramBenchmarkConfig,
    ForwardSinogramSuiteCase,
    benchmark_backend,
    benchmark_sinogram_mode,
    make_forward_projector_fixture,
    make_forward_sinogram_fixture,
    preset_config,
    run_forward_projector_benchmark,
    run_forward_projector_suite,
    run_forward_sinogram_benchmark,
    run_forward_sinogram_suite,
    sinogram_suite_cases,
    suite_cases,
    write_benchmark_json,
)
from .synthetic_results import (
    SyntheticBenchmarkResult,
    load_synthetic_benchmark_result,
    load_synthetic_benchmark_results,
    synthetic_benchmark_comparison_markdown,
    write_synthetic_benchmark_comparison_markdown,
)

__all__ = [
    "AcquisitionSpec",
    "AlignmentScenario",
    "ForwardProjectorBenchmarkConfig",
    "ForwardProjectorSuiteCase",
    "ForwardSinogramBenchmarkConfig",
    "ForwardSinogramSuiteCase",
    "PhantomSpec",
    "ScenarioExpectation",
    "ScenarioSuite",
    "SyntheticBenchmarkResult",
    "benchmark_backend",
    "benchmark_sinogram_mode",
    "load_synthetic_benchmark_result",
    "load_synthetic_benchmark_results",
    "make_forward_projector_fixture",
    "make_forward_sinogram_fixture",
    "phantom_spec",
    "preset_config",
    "run_forward_projector_benchmark",
    "run_forward_projector_suite",
    "run_forward_sinogram_benchmark",
    "run_forward_sinogram_suite",
    "scenario_by_slug",
    "scenario_catalog",
    "scenario_suite",
    "sinogram_suite_cases",
    "suite_cases",
    "synthetic_benchmark_comparison_markdown",
    "validate_scenario_catalog",
    "write_benchmark_json",
    "write_synthetic_benchmark_comparison_markdown",
]
